name: default
channels:
- conda-forge
- nodefaults
dependencies:
- python >=3.13.5,<3.14
- geopandas >=1.1.1,<2
- odc-stac >=0.4.0,<0.5
- ipykernel >=6.29.5,<7
- folium >=0.20.0,<0.21
- matplotlib >=3.10.3,<4
- mapclassify >=2.9.0,<3
- botocore >=1.39.2,<2
- pip
- pip:
  - pystac-client>=0.8.6, <0.9
  - planetary-computer>=1.0.0, <2

